### ISSUE TITLE
How to use local IP

### ISSUE THREAD

**Issue by MrGlasspoole** [stelgenhof/NTPClient#4]
Hi,

i have my own timeserver in my LAN.
How can i use the local IP instead of a domain?

**Comment by stelgenhof** [comment]
Yes, you can easily use an IP address as much as a domain name. For example:

`NTP.init((char *)"192.168.1.2", UTC0100);`

should work as well in your code.

**Comment by MrGlasspoole** [comment]
Oh that easy - thanks.

Is there a way to show LastSync in a format like "11:35:22 - 23.12.2017"?

**Comment by stelgenhof** [comment]
Sure, but functions `getLastSync` and `getFirstSync` return a Time Type (time_t) which can be converted to any format you like. You can use the `strftime` function to do that (you need to convert time_t to struct tm* first).

**Comment by stelgenhof** [comment]
Closing this as this issue was just a question. Please feel free to open a new issue, if you feel something is not working correctly :)
